### PR TITLE
Update deps due to security vulnerabilities for bumping version

### PR DESCRIPTION
**Pull request by ifraixedes**
The purpose of this PR is to promote this module to `v 1.0.0` as [mentioned in the README when it would happen]().

But, currently there were some security vulnerabilities in the used versions of the development dependencies, hence they have been updated and also the YARN support has been removed for easing the maintenance fo the module.

Once it be merged, the module version will be bumped with `npm version major` and the new version will be published in NPM.

### CODE REVIEW

**Comment by xlr-8** [comment]
I assume this is more related to @cycloidio/frontend-team ? Are you fine to merge it?

**Comment by EmilyRosina** [comment]
No idea what this is or how it's implemented :joy:

**Comment by ifraixedes** [comment]
It doesn't matter how it's implemented if you see the changes, it's only about to update dependencies.

**Comment by EmilyRosina** [comment]
@Seraf may have a better answer :woman_shrugging:

**Comment by adamwardecki** [comment]
Yep, it's ok to merge. It's only dependencies bump.

**Comment by ifraixedes** [comment]
Please, remember to update NPM version

**Pull request merged**
